name: Continuous Integration

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build --file Dockerfile --tag my_simple_code .

    - name: Run Tests
      run: docker run my_simple_code python -m unittest discover tests

