name: Calculator 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2
        with:
          repository: 'f-Xiaoxi/simple-ci-repo'
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3 # Replace 'x' with your desired Python version (e.g., 3.6, 3.7, 3.8, etc.)

      
      - name: Install dependencies
        run: |
          pip install pytest pytest-mock

      - name: Run pytest
        run: pytest test_calculator.py
